const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
  startListening: (data) => ipcRenderer.invoke('start-listening', data),
  stopListening: () => ipcRenderer.invoke('stop-listening'),
  stopAndReturnSetup: () => ipcRenderer.invoke('stop-and-return-setup'),
  closeOverlay: () => ipcRenderer.invoke('close-overlay'),
  copyToClipboard: (text) => ipcRenderer.invoke('copy-to-clipboard', text),
  captureCurrentWindow: () => ipcRenderer.invoke('capture-current-window'),
  extractScreenText: (data) => ipcRenderer.invoke('extract-screen-text', data),
  getAppConfig: () => ipcRenderer.invoke('get-app-config'),
  getSessionInfo: () => ipcRenderer.invoke('get-session-info'),
  validateLicense: (data) => ipcRenderer.invoke('validate-license', data),
  prepareContext: (data) => ipcRenderer.invoke('prepare-context', data),
  openOverlayAfterSetup: () => ipcRenderer.invoke('open-overlay-after-setup'),
  askLLM: (data) => ipcRenderer.invoke('ask-llm', data),
  startLLMStream: (data) => ipcRenderer.send('ask-llm-stream', data),
  cancelLLMStream: (requestId) => ipcRenderer.send('cancel-llm-stream', requestId),
  onLLMStream: (cb) => ipcRenderer.on('llm-stream', (_, data) => cb(data)),
  setOverlayCollapsed: (collapsed) => ipcRenderer.invoke('overlay-set-collapsed', collapsed),
  onTranscript: (cb) => ipcRenderer.on('transcript', (_, data) => cb(data)),
  onStatus: (cb) => ipcRenderer.on('status', (_, msg) => cb(msg)),
  onSpeechStart: (cb) => ipcRenderer.on('speech-started', () => cb()),
  onCredits: (cb) => ipcRenderer.on('credits', (_, data) => cb(data)),
});
